### ISSUE TITLE
do something with tweepy tracebacks

### ISSUE THREAD

**Issue by eichin** [eichin/thok-ztwitgw#5]
This one is recent, and isolated, and doesn't impact the service, but it points out that it would be nice to be a little prettier

``` python
    Traceback (most recent call last):
      File "/usr/lib/python2.6/runpy.py", line 122, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "/usr/lib/python2.6/runpy.py", line 34, in _run_code
        exec code in run_globals
      File "/home/eichin/gits/thok-ztwitgw/ztwitgw.py", line 210, in <module>
        process_new_twits(api)
      File "/home/eichin/gits/thok-ztwitgw/ztwitgw.py", line 170, in process_new_twits
        for twit in reversed(list(tweepy.Cursor(proto, since_id=since_id, include_entities=1).items())):
      File "/usr/lib/python2.6/dist-packages/tweepy/cursor.py", line 110, in next
        self.current_page = self.page_iterator.next()
      File "/usr/lib/python2.6/dist-packages/tweepy/cursor.py", line 85, in next
        items = self.method(page=self.current_page, *self.args, **self.kargs)
      File "/usr/lib/python2.6/dist-packages/tweepy/binder.py", line 179, in _call
        return method.execute()
      File "/usr/lib/python2.6/dist-packages/tweepy/binder.py", line 162, in execute
        raise TweepError(error_msg, resp)
    tweepy.error.TweepError: Twitter error response: status code = 502
```

**Comment by eichin** [comment]
(archiving now)
